/* eslint-disable react/no-unescaped-entities */
import { motion, useAnimation } from "framer-motion"
import { useInView } from "react-intersection-observer"
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [imgCount, setImgCount] = useState(0);

  const [menu, setMenu] = useState(false)

  const nextImage = () => {
    setImgCount(imgCount === 2 ? 2 : imgCount + 1)
  }

  const prevImage = () => {
    setImgCount(imgCount === 0 ? 0 :  imgCount - 1)
  }
  const controls = useAnimation()
  const [ref, inView] = useInView({
      threshold:0.3
  })

  const container = {
    hidden: { opacity:0, x:-50},
    show: {
      opacity:1,
      x : 0,
      transition: {
        duration: .7,
        staggerChildren: 0.3,
        delayChildren: 0.2
      }
    }
  };

  const items = {
    hidden: {opacity:0, x: 50 },
    show: {opacity:1, x: 0, transition: {duration:.5}}
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Room.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.headerContainer}>
        <div className={`heroImage${imgCount}`}>
          <header className={styles.headerMobile}>
            <div className={styles.hamburger}>
              <Image 
                onClick={() => setMenu(true)}
                src="/icon-hamburger.svg" 
                alt="open menu" 
                width={27} height={20} 
              />
            </div>
            
            <h2>room</h2>
          </header>

          <div 
     
            className={menu ? styles.menubar : styles.hide}>
            <div  className={styles.close}>
              <Image 
                onClick={() => setMenu(false)}
                src="/images/icon-close.svg" 
                width={20} height={20}
                alt="close menu"
              />
            </div>

            <ul>
              <li className={styles.anim_1}> <a href="">home</a> </li>
              <li className={styles.anim_2}> <a href="">shop</a> </li>
              <li className={styles.anim_3}> <a href="">about</a> </li>
              <li className={styles.anim_4}> <a href="">contact</a> </li>
            </ul>
          </div>

          <header className={styles.headerDesktop} >
            <h2>room</h2>

            <ul>
              <li className={styles.anim_1}> <a href="">home</a> </li>
              <li className={styles.anim_2}> <a href="">shop</a> </li>
              <li className={styles.anim_3}> <a href="">about</a> </li>
              <li className={styles.anim_4}> <a href="">contact</a> </li>
            </ul>
          </header>

          <div className={styles.navigate}>
            <Image onClick={prevImage} src="/images/icon-angle-left.svg" alt="navigate buttons"  width={20} height={20}  className={styles.directions} />
            <Image onClick={nextImage} src="/images/icon-angle-right.svg" alt="navigate buttons"  width={20} height={20} className={styles.directions}/>
          </div>
        </div>

        <section className={styles.headerSection}>
          {imgCount === 0 &&
            <>
              <h2>  Discover innovative ways to decorate</h2>
              <p> We provide unmatched quality, comfort, and style for property owners across the country. 
                Our experts combine form and function in bringing your vision to life. Create a room in your 
                own style with our collection and make your property a reflection of you and what you love.
              </p>
            </>
          }

          {imgCount === 1 &&
            <>
              <h2>We are available all across the globe</h2>
              <p>  With stores all over the world, it's easy for you to find furniture for your home or place of business. 
              Locally, we're in most major cities throughout the country. Find the branch nearest you using our 
              store locator. Any questions? Don't hesitate to contact us today.
              </p>
            </>
          }

          {imgCount === 2 &&
            <>
              <h2>Manufactured with the best material</h2>
              <p> Our modern furniture store provide a high level of quality. Our company has invested in advanced technology 
                  to ensure that every product is made as perfect and as consistent as possible. With three decades of 
                  experience in this industry, we understand what customers want for their home and office.
              </p>
            </>
          }

          <span>
            <a href=""> Shop now </a>
            <Image src="/images/icon-arrow.svg" width={40} height={15} alt = "Shop now"/>
          </span>

          <div>
            <Image onClick={prevImage} src="/images/icon-angle-left.svg" alt="navigate buttons"  width={20} height={20}  className={styles.arrow} />
            <Image onClick={nextImage} src="/images/icon-angle-right.svg" alt="navigate buttons"  width={20} height={20} className={styles.arrow}/>
          </div>
        </section>
      </div>

      <main className={styles.main}>
        <section>
          {imgCount === 0 &&
          <>
            <h2>  Discover innovative ways to decorate</h2>
            <p> We provide unmatched quality, comfort, and style for property owners across the country. 
              Our experts combine form and function in bringing your vision to life. Create a room in your 
              own style with our collection and make your property a reflection of you and what you love.
            </p>
            </>
          }

          {imgCount === 1 &&
          <>
            <h2>We are available all across the globe</h2>
            <p>  With stores all over the world, it's easy for you to find furniture for your home or place of business. 
            Locally, we're in most major cities throughout the country. Find the branch nearest you using our 
            store locator. Any questions? Don't hesitate to contact us today.
            </p>
            </>
          }

          {imgCount === 2 &&
          <>
            <h2>Manufactured with the best material</h2>
            <p> Our modern furniture store provide a high level of quality. Our company has invested in advanced technology 
                to ensure that every product is made as perfect and as consistent as possible. With three decades of 
                experience in this industry, we understand what customers want for their home and office.
            </p>
            </>
          }

          <div>
            <a href=""> Shop now </a>
            <Image 
              src="/images/icon-arrow.svg" 
              width={40} height={15} 
              alt = "Shop now"/>
          </div>
        </section>

        <section  className={styles.img}>
          <Image 
            src="/images/image-about-dark.jpg" 
            layout='fill'
            alt="furniture" 
            className={styles.about}
          />
        </section>

        <section className={styles.furniture}>
          <h2>About our furniture</h2>
          
          <p>Our multifunctional collection blends design and function to suit your individual taste.
            Make each room unique, or pick a cohesive theme that best express your interests and what
            inspires you. Find the furniture pieces you need, from traditional to contemporary styles
            or anything in between. Product specialists are available to help you create your dream space.
          </p>
        </section>

        <section className={styles.img}>
          <Image 
            src="/images/image-about-light.jpg" 
            layout='fill'
            alt="furniture" 
            className={styles.about}
          />
          
        </section>
      </main>
    </div>
  )
}
