import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [imgCount, setImgCount] = useState(0);

  const nextImage = () => {
    setImgCount(imgCount === 2 ? 2 : imgCount + 1)
  }

  const prevImage = () => {
    setImgCount(imgCount === 0 ? 0 :  imgCount - 1)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Room.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`heroImage${imgCount}`}>
        <header className={styles.header}>
          <Image src="/icon-hamburger.svg" alt="Vercel Logo" width={20} height={5} />
          <h2>room</h2>
        </header>

        <div className={styles.navigate}>
          <Image onClick={prevImage} src="/images/icon-angle-left.svg" alt="navigate buttons"  width={20} height={20}  className={styles.directions} />
          <Image onClick={nextImage} src="/images/icon-angle-right.svg" alt="navigate buttons"  width={20} height={20} className={styles.directions}/>
          {/* <button  >Left</button>
          <button  >Right</button> */}
        </div>
      </div>


      <main className={styles.main}>
        <section>
          <h2>  Discover innovative ways to decorate</h2>
          <p> We provide unmatched quality, comfort, and style for property owners across the country. 
            Our experts combine form and function in bringing your vision to life. Create a room in your 
            own style with our collection and make your property a reflection of you and what you love.
          </p>

          <div>
            <a href=""> Shop now </a>
            <Image src="/images/icon-arrow.svg" width={40} height={15} alt = "Shop now"/>
          </div>
        </section>

        <section>
          <Image src="/images/image-about-dark.jpg" width={40} height={15} alt="furniture" />
        </section>
      </main>
    </div>
  )
}
